//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `ReportsSystem.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package ReportsSystem;

public interface ReportsService extends com.zeroc.Ice.Object
{
    String getCitizenReports(String documento, int electionId, com.zeroc.Ice.Current current);

    String[] searchCitizenReports(String nombre, String apellido, int electionId, int limit, com.zeroc.Ice.Current current);

    String[] getMesaCitizenReports(int mesaId, int electionId, com.zeroc.Ice.Current current);

    boolean validateCitizenEligibility(String documento, com.zeroc.Ice.Current current);

    String getElectionReports(int electionId, com.zeroc.Ice.Current current);

    String[] getAvailableElections(com.zeroc.Ice.Current current);

    boolean areReportsReady(int electionId, com.zeroc.Ice.Current current);

    String getGeographicReports(int locationId, String locationType, int electionId, com.zeroc.Ice.Current current);

    void preloadReports(int electionId, com.zeroc.Ice.Current current);

    /** @hidden */
    static final String[] _iceIds =
    {
        "::Ice::Object",
        "::ReportsSystem::ReportsService"
    };

    @Override
    default String[] ice_ids(com.zeroc.Ice.Current current)
    {
        return _iceIds;
    }

    @Override
    default String ice_id(com.zeroc.Ice.Current current)
    {
        return ice_staticId();
    }

    static String ice_staticId()
    {
        return "::ReportsSystem::ReportsService";
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_getCitizenReports(ReportsService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_documento;
        int iceP_electionId;
        iceP_documento = istr.readString();
        iceP_electionId = istr.readInt();
        inS.endReadParams();
        String ret = obj.getCitizenReports(iceP_documento, iceP_electionId, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        ostr.writeString(ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_searchCitizenReports(ReportsService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_nombre;
        String iceP_apellido;
        int iceP_electionId;
        int iceP_limit;
        iceP_nombre = istr.readString();
        iceP_apellido = istr.readString();
        iceP_electionId = istr.readInt();
        iceP_limit = istr.readInt();
        inS.endReadParams();
        String[] ret = obj.searchCitizenReports(iceP_nombre, iceP_apellido, iceP_electionId, iceP_limit, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        ostr.writeStringSeq(ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_getMesaCitizenReports(ReportsService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        int iceP_mesaId;
        int iceP_electionId;
        iceP_mesaId = istr.readInt();
        iceP_electionId = istr.readInt();
        inS.endReadParams();
        String[] ret = obj.getMesaCitizenReports(iceP_mesaId, iceP_electionId, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        ostr.writeStringSeq(ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_validateCitizenEligibility(ReportsService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_documento;
        iceP_documento = istr.readString();
        inS.endReadParams();
        boolean ret = obj.validateCitizenEligibility(iceP_documento, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        ostr.writeBool(ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_getElectionReports(ReportsService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        int iceP_electionId;
        iceP_electionId = istr.readInt();
        inS.endReadParams();
        String ret = obj.getElectionReports(iceP_electionId, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        ostr.writeString(ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_getAvailableElections(ReportsService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        inS.readEmptyParams();
        String[] ret = obj.getAvailableElections(current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        ostr.writeStringSeq(ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_areReportsReady(ReportsService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        int iceP_electionId;
        iceP_electionId = istr.readInt();
        inS.endReadParams();
        boolean ret = obj.areReportsReady(iceP_electionId, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        ostr.writeBool(ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_getGeographicReports(ReportsService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        int iceP_locationId;
        String iceP_locationType;
        int iceP_electionId;
        iceP_locationId = istr.readInt();
        iceP_locationType = istr.readString();
        iceP_electionId = istr.readInt();
        inS.endReadParams();
        String ret = obj.getGeographicReports(iceP_locationId, iceP_locationType, iceP_electionId, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        ostr.writeString(ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_preloadReports(ReportsService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        int iceP_electionId;
        iceP_electionId = istr.readInt();
        inS.endReadParams();
        obj.preloadReports(iceP_electionId, current);
        return inS.setResult(inS.writeEmptyParams());
    }

    /** @hidden */
    final static String[] _iceOps =
    {
        "areReportsReady",
        "getAvailableElections",
        "getCitizenReports",
        "getElectionReports",
        "getGeographicReports",
        "getMesaCitizenReports",
        "ice_id",
        "ice_ids",
        "ice_isA",
        "ice_ping",
        "preloadReports",
        "searchCitizenReports",
        "validateCitizenEligibility"
    };

    /** @hidden */
    @Override
    default java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceDispatch(com.zeroc.IceInternal.Incoming in, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        int pos = java.util.Arrays.binarySearch(_iceOps, current.operation);
        if(pos < 0)
        {
            throw new com.zeroc.Ice.OperationNotExistException(current.id, current.facet, current.operation);
        }

        switch(pos)
        {
            case 0:
            {
                return _iceD_areReportsReady(this, in, current);
            }
            case 1:
            {
                return _iceD_getAvailableElections(this, in, current);
            }
            case 2:
            {
                return _iceD_getCitizenReports(this, in, current);
            }
            case 3:
            {
                return _iceD_getElectionReports(this, in, current);
            }
            case 4:
            {
                return _iceD_getGeographicReports(this, in, current);
            }
            case 5:
            {
                return _iceD_getMesaCitizenReports(this, in, current);
            }
            case 6:
            {
                return com.zeroc.Ice.Object._iceD_ice_id(this, in, current);
            }
            case 7:
            {
                return com.zeroc.Ice.Object._iceD_ice_ids(this, in, current);
            }
            case 8:
            {
                return com.zeroc.Ice.Object._iceD_ice_isA(this, in, current);
            }
            case 9:
            {
                return com.zeroc.Ice.Object._iceD_ice_ping(this, in, current);
            }
            case 10:
            {
                return _iceD_preloadReports(this, in, current);
            }
            case 11:
            {
                return _iceD_searchCitizenReports(this, in, current);
            }
            case 12:
            {
                return _iceD_validateCitizenEligibility(this, in, current);
            }
        }

        assert(false);
        throw new com.zeroc.Ice.OperationNotExistException(current.id, current.facet, current.operation);
    }
}
