//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `VotingSystem.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package VotingSystem;

public interface ConfigurationServicePrx extends com.zeroc.Ice.ObjectPrx
{
    default String getConfiguration(int mesaId, int electionId)
    {
        return getConfiguration(mesaId, electionId, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default String getConfiguration(int mesaId, int electionId, java.util.Map<String, String> context)
    {
        return _iceI_getConfigurationAsync(mesaId, electionId, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<java.lang.String> getConfigurationAsync(int mesaId, int electionId)
    {
        return _iceI_getConfigurationAsync(mesaId, electionId, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.String> getConfigurationAsync(int mesaId, int electionId, java.util.Map<String, String> context)
    {
        return _iceI_getConfigurationAsync(mesaId, electionId, context, false);
    }

    /**
     * @hidden
     * @param iceP_mesaId -
     * @param iceP_electionId -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.String> _iceI_getConfigurationAsync(int iceP_mesaId, int iceP_electionId, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.String> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getConfiguration", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeInt(iceP_mesaId);
                     ostr.writeInt(iceP_electionId);
                 }, istr -> {
                     String ret;
                     ret = istr.readString();
                     return ret;
                 });
        return f;
    }

    default boolean isConfigurationReady(int mesaId, int electionId)
    {
        return isConfigurationReady(mesaId, electionId, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default boolean isConfigurationReady(int mesaId, int electionId, java.util.Map<String, String> context)
    {
        return _iceI_isConfigurationReadyAsync(mesaId, electionId, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<java.lang.Boolean> isConfigurationReadyAsync(int mesaId, int electionId)
    {
        return _iceI_isConfigurationReadyAsync(mesaId, electionId, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.Boolean> isConfigurationReadyAsync(int mesaId, int electionId, java.util.Map<String, String> context)
    {
        return _iceI_isConfigurationReadyAsync(mesaId, electionId, context, false);
    }

    /**
     * @hidden
     * @param iceP_mesaId -
     * @param iceP_electionId -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.Boolean> _iceI_isConfigurationReadyAsync(int iceP_mesaId, int iceP_electionId, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.Boolean> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "isConfigurationReady", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeInt(iceP_mesaId);
                     ostr.writeInt(iceP_electionId);
                 }, istr -> {
                     boolean ret;
                     ret = istr.readBool();
                     return ret;
                 });
        return f;
    }

    default void preloadConfigurations(int[] mesaIds, int electionId)
    {
        preloadConfigurations(mesaIds, electionId, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void preloadConfigurations(int[] mesaIds, int electionId, java.util.Map<String, String> context)
    {
        _iceI_preloadConfigurationsAsync(mesaIds, electionId, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> preloadConfigurationsAsync(int[] mesaIds, int electionId)
    {
        return _iceI_preloadConfigurationsAsync(mesaIds, electionId, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> preloadConfigurationsAsync(int[] mesaIds, int electionId, java.util.Map<String, String> context)
    {
        return _iceI_preloadConfigurationsAsync(mesaIds, electionId, context, false);
    }

    /**
     * @hidden
     * @param iceP_mesaIds -
     * @param iceP_electionId -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_preloadConfigurationsAsync(int[] iceP_mesaIds, int iceP_electionId, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "preloadConfigurations", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeIntSeq(iceP_mesaIds);
                     ostr.writeInt(iceP_electionId);
                 }, null);
        return f;
    }

    default String[] getBatchConfigurations(int[] mesaIds, int electionId)
    {
        return getBatchConfigurations(mesaIds, electionId, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default String[] getBatchConfigurations(int[] mesaIds, int electionId, java.util.Map<String, String> context)
    {
        return _iceI_getBatchConfigurationsAsync(mesaIds, electionId, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<String[]> getBatchConfigurationsAsync(int[] mesaIds, int electionId)
    {
        return _iceI_getBatchConfigurationsAsync(mesaIds, electionId, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<String[]> getBatchConfigurationsAsync(int[] mesaIds, int electionId, java.util.Map<String, String> context)
    {
        return _iceI_getBatchConfigurationsAsync(mesaIds, electionId, context, false);
    }

    /**
     * @hidden
     * @param iceP_mesaIds -
     * @param iceP_electionId -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<String[]> _iceI_getBatchConfigurationsAsync(int[] iceP_mesaIds, int iceP_electionId, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<String[]> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getBatchConfigurations", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeIntSeq(iceP_mesaIds);
                     ostr.writeInt(iceP_electionId);
                 }, istr -> {
                     String[] ret;
                     ret = istr.readStringSeq();
                     return ret;
                 });
        return f;
    }

    default String[] getDepartmentConfigurations(int departmentId, int electionId)
    {
        return getDepartmentConfigurations(departmentId, electionId, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default String[] getDepartmentConfigurations(int departmentId, int electionId, java.util.Map<String, String> context)
    {
        return _iceI_getDepartmentConfigurationsAsync(departmentId, electionId, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<String[]> getDepartmentConfigurationsAsync(int departmentId, int electionId)
    {
        return _iceI_getDepartmentConfigurationsAsync(departmentId, electionId, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<String[]> getDepartmentConfigurationsAsync(int departmentId, int electionId, java.util.Map<String, String> context)
    {
        return _iceI_getDepartmentConfigurationsAsync(departmentId, electionId, context, false);
    }

    /**
     * @hidden
     * @param iceP_departmentId -
     * @param iceP_electionId -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<String[]> _iceI_getDepartmentConfigurationsAsync(int iceP_departmentId, int iceP_electionId, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<String[]> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getDepartmentConfigurations", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeInt(iceP_departmentId);
                     ostr.writeInt(iceP_electionId);
                 }, istr -> {
                     String[] ret;
                     ret = istr.readStringSeq();
                     return ret;
                 });
        return f;
    }

    default String[] getPuestoConfigurations(int puestoId, int electionId)
    {
        return getPuestoConfigurations(puestoId, electionId, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default String[] getPuestoConfigurations(int puestoId, int electionId, java.util.Map<String, String> context)
    {
        return _iceI_getPuestoConfigurationsAsync(puestoId, electionId, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<String[]> getPuestoConfigurationsAsync(int puestoId, int electionId)
    {
        return _iceI_getPuestoConfigurationsAsync(puestoId, electionId, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<String[]> getPuestoConfigurationsAsync(int puestoId, int electionId, java.util.Map<String, String> context)
    {
        return _iceI_getPuestoConfigurationsAsync(puestoId, electionId, context, false);
    }

    /**
     * @hidden
     * @param iceP_puestoId -
     * @param iceP_electionId -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<String[]> _iceI_getPuestoConfigurationsAsync(int iceP_puestoId, int iceP_electionId, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<String[]> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getPuestoConfigurations", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeInt(iceP_puestoId);
                     ostr.writeInt(iceP_electionId);
                 }, istr -> {
                     String[] ret;
                     ret = istr.readStringSeq();
                     return ret;
                 });
        return f;
    }

    default String getConfigurationStatistics(int electionId)
    {
        return getConfigurationStatistics(electionId, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default String getConfigurationStatistics(int electionId, java.util.Map<String, String> context)
    {
        return _iceI_getConfigurationStatisticsAsync(electionId, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<java.lang.String> getConfigurationStatisticsAsync(int electionId)
    {
        return _iceI_getConfigurationStatisticsAsync(electionId, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.String> getConfigurationStatisticsAsync(int electionId, java.util.Map<String, String> context)
    {
        return _iceI_getConfigurationStatisticsAsync(electionId, context, false);
    }

    /**
     * @hidden
     * @param iceP_electionId -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.String> _iceI_getConfigurationStatisticsAsync(int iceP_electionId, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.String> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getConfigurationStatistics", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeInt(iceP_electionId);
                 }, istr -> {
                     String ret;
                     ret = istr.readString();
                     return ret;
                 });
        return f;
    }

    default boolean isElectionReadyForConfiguration(int electionId)
    {
        return isElectionReadyForConfiguration(electionId, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default boolean isElectionReadyForConfiguration(int electionId, java.util.Map<String, String> context)
    {
        return _iceI_isElectionReadyForConfigurationAsync(electionId, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<java.lang.Boolean> isElectionReadyForConfigurationAsync(int electionId)
    {
        return _iceI_isElectionReadyForConfigurationAsync(electionId, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.Boolean> isElectionReadyForConfigurationAsync(int electionId, java.util.Map<String, String> context)
    {
        return _iceI_isElectionReadyForConfigurationAsync(electionId, context, false);
    }

    /**
     * @hidden
     * @param iceP_electionId -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.Boolean> _iceI_isElectionReadyForConfigurationAsync(int iceP_electionId, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.Boolean> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "isElectionReadyForConfiguration", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeInt(iceP_electionId);
                 }, istr -> {
                     boolean ret;
                     ret = istr.readBool();
                     return ret;
                 });
        return f;
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ConfigurationServicePrx checkedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, ice_staticId(), ConfigurationServicePrx.class, _ConfigurationServicePrxI.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ConfigurationServicePrx checkedCast(com.zeroc.Ice.ObjectPrx obj, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, context, ice_staticId(), ConfigurationServicePrx.class, _ConfigurationServicePrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ConfigurationServicePrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, ice_staticId(), ConfigurationServicePrx.class, _ConfigurationServicePrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ConfigurationServicePrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, context, ice_staticId(), ConfigurationServicePrx.class, _ConfigurationServicePrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @return A proxy for this type.
     **/
    static ConfigurationServicePrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, ConfigurationServicePrx.class, _ConfigurationServicePrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    static ConfigurationServicePrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, facet, ConfigurationServicePrx.class, _ConfigurationServicePrxI.class);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the per-proxy context.
     * @param newContext The context for the new proxy.
     * @return A proxy with the specified per-proxy context.
     **/
    @Override
    default ConfigurationServicePrx ice_context(java.util.Map<String, String> newContext)
    {
        return (ConfigurationServicePrx)_ice_context(newContext);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the adapter ID.
     * @param newAdapterId The adapter ID for the new proxy.
     * @return A proxy with the specified adapter ID.
     **/
    @Override
    default ConfigurationServicePrx ice_adapterId(String newAdapterId)
    {
        return (ConfigurationServicePrx)_ice_adapterId(newAdapterId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoints.
     * @param newEndpoints The endpoints for the new proxy.
     * @return A proxy with the specified endpoints.
     **/
    @Override
    default ConfigurationServicePrx ice_endpoints(com.zeroc.Ice.Endpoint[] newEndpoints)
    {
        return (ConfigurationServicePrx)_ice_endpoints(newEndpoints);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator cache timeout.
     * @param newTimeout The new locator cache timeout (in seconds).
     * @return A proxy with the specified locator cache timeout.
     **/
    @Override
    default ConfigurationServicePrx ice_locatorCacheTimeout(int newTimeout)
    {
        return (ConfigurationServicePrx)_ice_locatorCacheTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the invocation timeout.
     * @param newTimeout The new invocation timeout (in seconds).
     * @return A proxy with the specified invocation timeout.
     **/
    @Override
    default ConfigurationServicePrx ice_invocationTimeout(int newTimeout)
    {
        return (ConfigurationServicePrx)_ice_invocationTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for connection caching.
     * @param newCache <code>true</code> if the new proxy should cache connections; <code>false</code> otherwise.
     * @return A proxy with the specified caching policy.
     **/
    @Override
    default ConfigurationServicePrx ice_connectionCached(boolean newCache)
    {
        return (ConfigurationServicePrx)_ice_connectionCached(newCache);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoint selection policy.
     * @param newType The new endpoint selection policy.
     * @return A proxy with the specified endpoint selection policy.
     **/
    @Override
    default ConfigurationServicePrx ice_endpointSelection(com.zeroc.Ice.EndpointSelectionType newType)
    {
        return (ConfigurationServicePrx)_ice_endpointSelection(newType);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for how it selects endpoints.
     * @param b If <code>b</code> is <code>true</code>, only endpoints that use a secure transport are
     * used by the new proxy. If <code>b</code> is false, the returned proxy uses both secure and
     * insecure endpoints.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default ConfigurationServicePrx ice_secure(boolean b)
    {
        return (ConfigurationServicePrx)_ice_secure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the encoding used to marshal parameters.
     * @param e The encoding version to use to marshal request parameters.
     * @return A proxy with the specified encoding version.
     **/
    @Override
    default ConfigurationServicePrx ice_encodingVersion(com.zeroc.Ice.EncodingVersion e)
    {
        return (ConfigurationServicePrx)_ice_encodingVersion(e);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its endpoint selection policy.
     * @param b If <code>b</code> is <code>true</code>, the new proxy will use secure endpoints for invocations
     * and only use insecure endpoints if an invocation cannot be made via secure endpoints. If <code>b</code> is
     * <code>false</code>, the proxy prefers insecure endpoints to secure ones.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default ConfigurationServicePrx ice_preferSecure(boolean b)
    {
        return (ConfigurationServicePrx)_ice_preferSecure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the router.
     * @param router The router for the new proxy.
     * @return A proxy with the specified router.
     **/
    @Override
    default ConfigurationServicePrx ice_router(com.zeroc.Ice.RouterPrx router)
    {
        return (ConfigurationServicePrx)_ice_router(router);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator.
     * @param locator The locator for the new proxy.
     * @return A proxy with the specified locator.
     **/
    @Override
    default ConfigurationServicePrx ice_locator(com.zeroc.Ice.LocatorPrx locator)
    {
        return (ConfigurationServicePrx)_ice_locator(locator);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for collocation optimization.
     * @param b <code>true</code> if the new proxy enables collocation optimization; <code>false</code> otherwise.
     * @return A proxy with the specified collocation optimization.
     **/
    @Override
    default ConfigurationServicePrx ice_collocationOptimized(boolean b)
    {
        return (ConfigurationServicePrx)_ice_collocationOptimized(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses twoway invocations.
     * @return A proxy that uses twoway invocations.
     **/
    @Override
    default ConfigurationServicePrx ice_twoway()
    {
        return (ConfigurationServicePrx)_ice_twoway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses oneway invocations.
     * @return A proxy that uses oneway invocations.
     **/
    @Override
    default ConfigurationServicePrx ice_oneway()
    {
        return (ConfigurationServicePrx)_ice_oneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch oneway invocations.
     * @return A proxy that uses batch oneway invocations.
     **/
    @Override
    default ConfigurationServicePrx ice_batchOneway()
    {
        return (ConfigurationServicePrx)_ice_batchOneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses datagram invocations.
     * @return A proxy that uses datagram invocations.
     **/
    @Override
    default ConfigurationServicePrx ice_datagram()
    {
        return (ConfigurationServicePrx)_ice_datagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch datagram invocations.
     * @return A proxy that uses batch datagram invocations.
     **/
    @Override
    default ConfigurationServicePrx ice_batchDatagram()
    {
        return (ConfigurationServicePrx)_ice_batchDatagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, except for compression.
     * @param co <code>true</code> enables compression for the new proxy; <code>false</code> disables compression.
     * @return A proxy with the specified compression setting.
     **/
    @Override
    default ConfigurationServicePrx ice_compress(boolean co)
    {
        return (ConfigurationServicePrx)_ice_compress(co);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection timeout setting.
     * @param t The connection timeout for the proxy in milliseconds.
     * @return A proxy with the specified timeout.
     **/
    @Override
    default ConfigurationServicePrx ice_timeout(int t)
    {
        return (ConfigurationServicePrx)_ice_timeout(t);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection ID.
     * @param connectionId The connection ID for the new proxy. An empty string removes the connection ID.
     * @return A proxy with the specified connection ID.
     **/
    @Override
    default ConfigurationServicePrx ice_connectionId(String connectionId)
    {
        return (ConfigurationServicePrx)_ice_connectionId(connectionId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except it's a fixed proxy bound
     * the given connection.@param connection The fixed proxy connection.
     * @return A fixed proxy bound to the given connection.
     **/
    @Override
    default ConfigurationServicePrx ice_fixed(com.zeroc.Ice.Connection connection)
    {
        return (ConfigurationServicePrx)_ice_fixed(connection);
    }

    static String ice_staticId()
    {
        return "::VotingSystem::ConfigurationService";
    }
}
