//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `VotingSystem.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package VotingSystem;

public class VotingConfiguration extends com.zeroc.Ice.Value
{
    public VotingConfiguration()
    {
        this.mesaInfo = new MesaInfo();
        this.electionInfo = new ElectionInfo();
        this.packageVersion = "";
    }

    public VotingConfiguration(MesaInfo mesaInfo, ElectionInfo electionInfo, Candidate[] candidates, Citizen[] citizens, String packageVersion, long generationTimestamp)
    {
        this.mesaInfo = mesaInfo;
        this.electionInfo = electionInfo;
        this.candidates = candidates;
        this.citizens = citizens;
        this.packageVersion = packageVersion;
        this.generationTimestamp = generationTimestamp;
    }

    public MesaInfo mesaInfo;

    public ElectionInfo electionInfo;

    public Candidate[] candidates;

    public Citizen[] citizens;

    public String packageVersion;

    public long generationTimestamp;

    public VotingConfiguration clone()
    {
        return (VotingConfiguration)super.clone();
    }

    public static String ice_staticId()
    {
        return "::VotingSystem::VotingConfiguration";
    }

    @Override
    public String ice_id()
    {
        return ice_staticId();
    }

    /** @hidden */
    public static final long serialVersionUID = -1473511242L;

    /** @hidden */
    @Override
    protected void _iceWriteImpl(com.zeroc.Ice.OutputStream ostr_)
    {
        ostr_.startSlice(ice_staticId(), -1, true);
        MesaInfo.ice_write(ostr_, mesaInfo);
        ElectionInfo.ice_write(ostr_, electionInfo);
        CandidateSeqHelper.write(ostr_, candidates);
        CitizenSeqHelper.write(ostr_, citizens);
        ostr_.writeString(packageVersion);
        ostr_.writeLong(generationTimestamp);
        ostr_.endSlice();
    }

    /** @hidden */
    @Override
    protected void _iceReadImpl(com.zeroc.Ice.InputStream istr_)
    {
        istr_.startSlice();
        mesaInfo = MesaInfo.ice_read(istr_);
        electionInfo = ElectionInfo.ice_read(istr_);
        candidates = CandidateSeqHelper.read(istr_);
        citizens = CitizenSeqHelper.read(istr_);
        packageVersion = istr_.readString();
        generationTimestamp = istr_.readLong();
        istr_.endSlice();
    }
}
