//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `VoteNotification.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package VoteNotification;

public interface VoteNotifierPrx extends com.zeroc.Ice.ObjectPrx
{
    default void registerObserver(VoteObserverPrx observer, int electionId)
    {
        registerObserver(observer, electionId, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void registerObserver(VoteObserverPrx observer, int electionId, java.util.Map<String, String> context)
    {
        _iceI_registerObserverAsync(observer, electionId, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> registerObserverAsync(VoteObserverPrx observer, int electionId)
    {
        return _iceI_registerObserverAsync(observer, electionId, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> registerObserverAsync(VoteObserverPrx observer, int electionId, java.util.Map<String, String> context)
    {
        return _iceI_registerObserverAsync(observer, electionId, context, false);
    }

    /**
     * @hidden
     * @param iceP_observer -
     * @param iceP_electionId -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_registerObserverAsync(VoteObserverPrx iceP_observer, int iceP_electionId, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "registerObserver", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeProxy(iceP_observer);
                     ostr.writeInt(iceP_electionId);
                 }, null);
        return f;
    }

    default void unregisterObserver(VoteObserverPrx observer, int electionId)
    {
        unregisterObserver(observer, electionId, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void unregisterObserver(VoteObserverPrx observer, int electionId, java.util.Map<String, String> context)
    {
        _iceI_unregisterObserverAsync(observer, electionId, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> unregisterObserverAsync(VoteObserverPrx observer, int electionId)
    {
        return _iceI_unregisterObserverAsync(observer, electionId, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> unregisterObserverAsync(VoteObserverPrx observer, int electionId, java.util.Map<String, String> context)
    {
        return _iceI_unregisterObserverAsync(observer, electionId, context, false);
    }

    /**
     * @hidden
     * @param iceP_observer -
     * @param iceP_electionId -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_unregisterObserverAsync(VoteObserverPrx iceP_observer, int iceP_electionId, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "unregisterObserver", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeProxy(iceP_observer);
                     ostr.writeInt(iceP_electionId);
                 }, null);
        return f;
    }

    default int getObserverCount(int electionId)
    {
        return getObserverCount(electionId, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default int getObserverCount(int electionId, java.util.Map<String, String> context)
    {
        return _iceI_getObserverCountAsync(electionId, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<java.lang.Integer> getObserverCountAsync(int electionId)
    {
        return _iceI_getObserverCountAsync(electionId, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.Integer> getObserverCountAsync(int electionId, java.util.Map<String, String> context)
    {
        return _iceI_getObserverCountAsync(electionId, context, false);
    }

    /**
     * @hidden
     * @param iceP_electionId -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.Integer> _iceI_getObserverCountAsync(int iceP_electionId, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.Integer> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getObserverCount", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeInt(iceP_electionId);
                 }, istr -> {
                     int ret;
                     ret = istr.readInt();
                     return ret;
                 });
        return f;
    }

    default void forceResultsUpdate(int electionId)
    {
        forceResultsUpdate(electionId, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void forceResultsUpdate(int electionId, java.util.Map<String, String> context)
    {
        _iceI_forceResultsUpdateAsync(electionId, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> forceResultsUpdateAsync(int electionId)
    {
        return _iceI_forceResultsUpdateAsync(electionId, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> forceResultsUpdateAsync(int electionId, java.util.Map<String, String> context)
    {
        return _iceI_forceResultsUpdateAsync(electionId, context, false);
    }

    /**
     * @hidden
     * @param iceP_electionId -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_forceResultsUpdateAsync(int iceP_electionId, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "forceResultsUpdate", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeInt(iceP_electionId);
                 }, null);
        return f;
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static VoteNotifierPrx checkedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, ice_staticId(), VoteNotifierPrx.class, _VoteNotifierPrxI.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static VoteNotifierPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, context, ice_staticId(), VoteNotifierPrx.class, _VoteNotifierPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static VoteNotifierPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, ice_staticId(), VoteNotifierPrx.class, _VoteNotifierPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static VoteNotifierPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, context, ice_staticId(), VoteNotifierPrx.class, _VoteNotifierPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @return A proxy for this type.
     **/
    static VoteNotifierPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, VoteNotifierPrx.class, _VoteNotifierPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    static VoteNotifierPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, facet, VoteNotifierPrx.class, _VoteNotifierPrxI.class);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the per-proxy context.
     * @param newContext The context for the new proxy.
     * @return A proxy with the specified per-proxy context.
     **/
    @Override
    default VoteNotifierPrx ice_context(java.util.Map<String, String> newContext)
    {
        return (VoteNotifierPrx)_ice_context(newContext);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the adapter ID.
     * @param newAdapterId The adapter ID for the new proxy.
     * @return A proxy with the specified adapter ID.
     **/
    @Override
    default VoteNotifierPrx ice_adapterId(String newAdapterId)
    {
        return (VoteNotifierPrx)_ice_adapterId(newAdapterId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoints.
     * @param newEndpoints The endpoints for the new proxy.
     * @return A proxy with the specified endpoints.
     **/
    @Override
    default VoteNotifierPrx ice_endpoints(com.zeroc.Ice.Endpoint[] newEndpoints)
    {
        return (VoteNotifierPrx)_ice_endpoints(newEndpoints);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator cache timeout.
     * @param newTimeout The new locator cache timeout (in seconds).
     * @return A proxy with the specified locator cache timeout.
     **/
    @Override
    default VoteNotifierPrx ice_locatorCacheTimeout(int newTimeout)
    {
        return (VoteNotifierPrx)_ice_locatorCacheTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the invocation timeout.
     * @param newTimeout The new invocation timeout (in seconds).
     * @return A proxy with the specified invocation timeout.
     **/
    @Override
    default VoteNotifierPrx ice_invocationTimeout(int newTimeout)
    {
        return (VoteNotifierPrx)_ice_invocationTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for connection caching.
     * @param newCache <code>true</code> if the new proxy should cache connections; <code>false</code> otherwise.
     * @return A proxy with the specified caching policy.
     **/
    @Override
    default VoteNotifierPrx ice_connectionCached(boolean newCache)
    {
        return (VoteNotifierPrx)_ice_connectionCached(newCache);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoint selection policy.
     * @param newType The new endpoint selection policy.
     * @return A proxy with the specified endpoint selection policy.
     **/
    @Override
    default VoteNotifierPrx ice_endpointSelection(com.zeroc.Ice.EndpointSelectionType newType)
    {
        return (VoteNotifierPrx)_ice_endpointSelection(newType);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for how it selects endpoints.
     * @param b If <code>b</code> is <code>true</code>, only endpoints that use a secure transport are
     * used by the new proxy. If <code>b</code> is false, the returned proxy uses both secure and
     * insecure endpoints.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default VoteNotifierPrx ice_secure(boolean b)
    {
        return (VoteNotifierPrx)_ice_secure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the encoding used to marshal parameters.
     * @param e The encoding version to use to marshal request parameters.
     * @return A proxy with the specified encoding version.
     **/
    @Override
    default VoteNotifierPrx ice_encodingVersion(com.zeroc.Ice.EncodingVersion e)
    {
        return (VoteNotifierPrx)_ice_encodingVersion(e);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its endpoint selection policy.
     * @param b If <code>b</code> is <code>true</code>, the new proxy will use secure endpoints for invocations
     * and only use insecure endpoints if an invocation cannot be made via secure endpoints. If <code>b</code> is
     * <code>false</code>, the proxy prefers insecure endpoints to secure ones.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default VoteNotifierPrx ice_preferSecure(boolean b)
    {
        return (VoteNotifierPrx)_ice_preferSecure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the router.
     * @param router The router for the new proxy.
     * @return A proxy with the specified router.
     **/
    @Override
    default VoteNotifierPrx ice_router(com.zeroc.Ice.RouterPrx router)
    {
        return (VoteNotifierPrx)_ice_router(router);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator.
     * @param locator The locator for the new proxy.
     * @return A proxy with the specified locator.
     **/
    @Override
    default VoteNotifierPrx ice_locator(com.zeroc.Ice.LocatorPrx locator)
    {
        return (VoteNotifierPrx)_ice_locator(locator);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for collocation optimization.
     * @param b <code>true</code> if the new proxy enables collocation optimization; <code>false</code> otherwise.
     * @return A proxy with the specified collocation optimization.
     **/
    @Override
    default VoteNotifierPrx ice_collocationOptimized(boolean b)
    {
        return (VoteNotifierPrx)_ice_collocationOptimized(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses twoway invocations.
     * @return A proxy that uses twoway invocations.
     **/
    @Override
    default VoteNotifierPrx ice_twoway()
    {
        return (VoteNotifierPrx)_ice_twoway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses oneway invocations.
     * @return A proxy that uses oneway invocations.
     **/
    @Override
    default VoteNotifierPrx ice_oneway()
    {
        return (VoteNotifierPrx)_ice_oneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch oneway invocations.
     * @return A proxy that uses batch oneway invocations.
     **/
    @Override
    default VoteNotifierPrx ice_batchOneway()
    {
        return (VoteNotifierPrx)_ice_batchOneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses datagram invocations.
     * @return A proxy that uses datagram invocations.
     **/
    @Override
    default VoteNotifierPrx ice_datagram()
    {
        return (VoteNotifierPrx)_ice_datagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch datagram invocations.
     * @return A proxy that uses batch datagram invocations.
     **/
    @Override
    default VoteNotifierPrx ice_batchDatagram()
    {
        return (VoteNotifierPrx)_ice_batchDatagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, except for compression.
     * @param co <code>true</code> enables compression for the new proxy; <code>false</code> disables compression.
     * @return A proxy with the specified compression setting.
     **/
    @Override
    default VoteNotifierPrx ice_compress(boolean co)
    {
        return (VoteNotifierPrx)_ice_compress(co);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection timeout setting.
     * @param t The connection timeout for the proxy in milliseconds.
     * @return A proxy with the specified timeout.
     **/
    @Override
    default VoteNotifierPrx ice_timeout(int t)
    {
        return (VoteNotifierPrx)_ice_timeout(t);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection ID.
     * @param connectionId The connection ID for the new proxy. An empty string removes the connection ID.
     * @return A proxy with the specified connection ID.
     **/
    @Override
    default VoteNotifierPrx ice_connectionId(String connectionId)
    {
        return (VoteNotifierPrx)_ice_connectionId(connectionId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except it's a fixed proxy bound
     * the given connection.@param connection The fixed proxy connection.
     * @return A fixed proxy bound to the given connection.
     **/
    @Override
    default VoteNotifierPrx ice_fixed(com.zeroc.Ice.Connection connection)
    {
        return (VoteNotifierPrx)_ice_fixed(connection);
    }

    static String ice_staticId()
    {
        return "::VoteNotification::VoteNotifier";
    }
}
