//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `ReportsSystem.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package ReportsSystem;

public class CandidateInfo implements java.lang.Cloneable,
                                      java.io.Serializable
{
    public int id;

    public String nombre;

    public String partido;

    public int voteCount;

    public double percentage;

    public CandidateInfo()
    {
        this.nombre = "";
        this.partido = "";
    }

    public CandidateInfo(int id, String nombre, String partido, int voteCount, double percentage)
    {
        this.id = id;
        this.nombre = nombre;
        this.partido = partido;
        this.voteCount = voteCount;
        this.percentage = percentage;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        CandidateInfo r = null;
        if(rhs instanceof CandidateInfo)
        {
            r = (CandidateInfo)rhs;
        }

        if(r != null)
        {
            if(this.id != r.id)
            {
                return false;
            }
            if(this.nombre != r.nombre)
            {
                if(this.nombre == null || r.nombre == null || !this.nombre.equals(r.nombre))
                {
                    return false;
                }
            }
            if(this.partido != r.partido)
            {
                if(this.partido == null || r.partido == null || !this.partido.equals(r.partido))
                {
                    return false;
                }
            }
            if(this.voteCount != r.voteCount)
            {
                return false;
            }
            if(this.percentage != r.percentage)
            {
                return false;
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::ReportsSystem::CandidateInfo");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, id);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, nombre);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, partido);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, voteCount);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, percentage);
        return h_;
    }

    public CandidateInfo clone()
    {
        CandidateInfo c = null;
        try
        {
            c = (CandidateInfo)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeInt(this.id);
        ostr.writeString(this.nombre);
        ostr.writeString(this.partido);
        ostr.writeInt(this.voteCount);
        ostr.writeDouble(this.percentage);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.id = istr.readInt();
        this.nombre = istr.readString();
        this.partido = istr.readString();
        this.voteCount = istr.readInt();
        this.percentage = istr.readDouble();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, CandidateInfo v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public CandidateInfo ice_read(com.zeroc.Ice.InputStream istr)
    {
        CandidateInfo v = new CandidateInfo();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<CandidateInfo> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, CandidateInfo v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<CandidateInfo> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            return java.util.Optional.of(CandidateInfo.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final CandidateInfo _nullMarshalValue = new CandidateInfo();

    /** @hidden */
    public static final long serialVersionUID = -3080856716238319587L;
}
