//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `ReportsSystem.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package ReportsSystem;

public class ElectionResults implements java.lang.Cloneable,
                                        java.io.Serializable
{
    public ElectionInfo election;

    public CandidateInfo[] candidateResults;

    public int totalVotes;

    public long totalEligibleVoters;

    public double participationPercentage;

    public long generationTimestamp;

    public ElectionResults()
    {
        this.election = new ElectionInfo();
    }

    public ElectionResults(ElectionInfo election, CandidateInfo[] candidateResults, int totalVotes, long totalEligibleVoters, double participationPercentage, long generationTimestamp)
    {
        this.election = election;
        this.candidateResults = candidateResults;
        this.totalVotes = totalVotes;
        this.totalEligibleVoters = totalEligibleVoters;
        this.participationPercentage = participationPercentage;
        this.generationTimestamp = generationTimestamp;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        ElectionResults r = null;
        if(rhs instanceof ElectionResults)
        {
            r = (ElectionResults)rhs;
        }

        if(r != null)
        {
            if(this.election != r.election)
            {
                if(this.election == null || r.election == null || !this.election.equals(r.election))
                {
                    return false;
                }
            }
            if(!java.util.Arrays.equals(this.candidateResults, r.candidateResults))
            {
                return false;
            }
            if(this.totalVotes != r.totalVotes)
            {
                return false;
            }
            if(this.totalEligibleVoters != r.totalEligibleVoters)
            {
                return false;
            }
            if(this.participationPercentage != r.participationPercentage)
            {
                return false;
            }
            if(this.generationTimestamp != r.generationTimestamp)
            {
                return false;
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::ReportsSystem::ElectionResults");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, election);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, candidateResults);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, totalVotes);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, totalEligibleVoters);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, participationPercentage);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, generationTimestamp);
        return h_;
    }

    public ElectionResults clone()
    {
        ElectionResults c = null;
        try
        {
            c = (ElectionResults)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ElectionInfo.ice_write(ostr, this.election);
        CandidateSeqHelper.write(ostr, this.candidateResults);
        ostr.writeInt(this.totalVotes);
        ostr.writeLong(this.totalEligibleVoters);
        ostr.writeDouble(this.participationPercentage);
        ostr.writeLong(this.generationTimestamp);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.election = ElectionInfo.ice_read(istr);
        this.candidateResults = CandidateSeqHelper.read(istr);
        this.totalVotes = istr.readInt();
        this.totalEligibleVoters = istr.readLong();
        this.participationPercentage = istr.readDouble();
        this.generationTimestamp = istr.readLong();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, ElectionResults v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public ElectionResults ice_read(com.zeroc.Ice.InputStream istr)
    {
        ElectionResults v = new ElectionResults();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<ElectionResults> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, ElectionResults v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<ElectionResults> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            return java.util.Optional.of(ElectionResults.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final ElectionResults _nullMarshalValue = new ElectionResults();

    /** @hidden */
    public static final long serialVersionUID = -3394305726419018984L;
}
