//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `ReportsSystem.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package ReportsSystem;

/**
 * Helper class for marshaling/unmarshaling ElectionSeq.
 **/
public final class ElectionSeqHelper
{
    public static void write(com.zeroc.Ice.OutputStream ostr, ElectionInfo[] v)
    {
        if(v == null)
        {
            ostr.writeSize(0);
        }
        else
        {
            ostr.writeSize(v.length);
            for(int i0 = 0; i0 < v.length; i0++)
            {
                ElectionInfo.ice_write(ostr, v[i0]);
            }
        }
    }

    public static ElectionInfo[] read(com.zeroc.Ice.InputStream istr)
    {
        final ElectionInfo[] v;
        final int len0 = istr.readAndCheckSeqSize(22);
        v = new ElectionInfo[len0];
        for(int i0 = 0; i0 < len0; i0++)
        {
            v[i0] = ElectionInfo.ice_read(istr);
        }
        return v;
    }

    public static void write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<ElectionInfo[]> v)
    {
        if(v != null && v.isPresent())
        {
            write(ostr, tag, v.get());
        }
    }

    public static void write(com.zeroc.Ice.OutputStream ostr, int tag, ElectionInfo[] v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ElectionSeqHelper.write(ostr, v);
            ostr.endSize(pos);
        }
    }

    public static java.util.Optional<ElectionInfo[]> read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            ElectionInfo[] v;
            v = ElectionSeqHelper.read(istr);
            return java.util.Optional.of(v);
        }
        else
        {
            return java.util.Optional.empty();
        }
    }
}
