//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `ReportsSystem.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package ReportsSystem;

public class ElectionReportsConfiguration extends com.zeroc.Ice.Value
{
    public ElectionReportsConfiguration()
    {
        this.results = new ElectionResults();
        this.nationalStats = new GeographicStats();
        this.packageVersion = "";
    }

    public ElectionReportsConfiguration(ElectionResults results, GeographicStats nationalStats, LocationInfo[] availableLocations, String packageVersion, long generationTimestamp)
    {
        this.results = results;
        this.nationalStats = nationalStats;
        this.availableLocations = availableLocations;
        this.packageVersion = packageVersion;
        this.generationTimestamp = generationTimestamp;
    }

    public ElectionResults results;

    public GeographicStats nationalStats;

    public LocationInfo[] availableLocations;

    public String packageVersion;

    public long generationTimestamp;

    public ElectionReportsConfiguration clone()
    {
        return (ElectionReportsConfiguration)super.clone();
    }

    public static String ice_staticId()
    {
        return "::ReportsSystem::ElectionReportsConfiguration";
    }

    @Override
    public String ice_id()
    {
        return ice_staticId();
    }

    /** @hidden */
    public static final long serialVersionUID = -8545761299497980118L;

    /** @hidden */
    @Override
    protected void _iceWriteImpl(com.zeroc.Ice.OutputStream ostr_)
    {
        ostr_.startSlice(ice_staticId(), -1, true);
        ElectionResults.ice_write(ostr_, results);
        GeographicStats.ice_write(ostr_, nationalStats);
        LocationSeqHelper.write(ostr_, availableLocations);
        ostr_.writeString(packageVersion);
        ostr_.writeLong(generationTimestamp);
        ostr_.endSlice();
    }

    /** @hidden */
    @Override
    protected void _iceReadImpl(com.zeroc.Ice.InputStream istr_)
    {
        istr_.startSlice();
        results = ElectionResults.ice_read(istr_);
        nationalStats = GeographicStats.ice_read(istr_);
        availableLocations = LocationSeqHelper.read(istr_);
        packageVersion = istr_.readString();
        generationTimestamp = istr_.readLong();
        istr_.endSlice();
    }
}
