//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `ReportsSystem.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package ReportsSystem;

/**
 * Helper class for marshaling/unmarshaling LocationSeq.
 **/
public final class LocationSeqHelper
{
    public static void write(com.zeroc.Ice.OutputStream ostr, LocationInfo[] v)
    {
        if(v == null)
        {
            ostr.writeSize(0);
        }
        else
        {
            ostr.writeSize(v.length);
            for(int i0 = 0; i0 < v.length; i0++)
            {
                LocationInfo.ice_write(ostr, v[i0]);
            }
        }
    }

    public static LocationInfo[] read(com.zeroc.Ice.InputStream istr)
    {
        final LocationInfo[] v;
        final int len0 = istr.readAndCheckSeqSize(28);
        v = new LocationInfo[len0];
        for(int i0 = 0; i0 < len0; i0++)
        {
            v[i0] = LocationInfo.ice_read(istr);
        }
        return v;
    }

    public static void write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<LocationInfo[]> v)
    {
        if(v != null && v.isPresent())
        {
            write(ostr, tag, v.get());
        }
    }

    public static void write(com.zeroc.Ice.OutputStream ostr, int tag, LocationInfo[] v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            LocationSeqHelper.write(ostr, v);
            ostr.endSize(pos);
        }
    }

    public static java.util.Optional<LocationInfo[]> read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            LocationInfo[] v;
            v = LocationSeqHelper.read(istr);
            return java.util.Optional.of(v);
        }
        else
        {
            return java.util.Optional.empty();
        }
    }
}
