//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `VotingsSystem.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package VotingsSystem;

public interface ConfigurationService extends com.zeroc.Ice.Object
{
    String getConfiguration(int mesaId, int electionId, com.zeroc.Ice.Current current);

    boolean isConfigurationReady(int mesaId, int electionId, com.zeroc.Ice.Current current);

    void preloadConfigurations(int[] mesaIds, int electionId, com.zeroc.Ice.Current current);

    String[] getBatchConfigurations(int[] mesaIds, int electionId, com.zeroc.Ice.Current current);

    String[] getDepartmentConfigurations(int departmentId, int electionId, com.zeroc.Ice.Current current);

    String[] getPuestoConfigurations(int puestoId, int electionId, com.zeroc.Ice.Current current);

    String getConfigurationStatistics(int electionId, com.zeroc.Ice.Current current);

    boolean isElectionReadyForConfiguration(int electionId, com.zeroc.Ice.Current current);

    /** @hidden */
    static final String[] _iceIds =
    {
        "::Ice::Object",
        "::VotingsSystem::ConfigurationService"
    };

    @Override
    default String[] ice_ids(com.zeroc.Ice.Current current)
    {
        return _iceIds;
    }

    @Override
    default String ice_id(com.zeroc.Ice.Current current)
    {
        return ice_staticId();
    }

    static String ice_staticId()
    {
        return "::VotingsSystem::ConfigurationService";
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_getConfiguration(ConfigurationService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        int iceP_mesaId;
        int iceP_electionId;
        iceP_mesaId = istr.readInt();
        iceP_electionId = istr.readInt();
        inS.endReadParams();
        String ret = obj.getConfiguration(iceP_mesaId, iceP_electionId, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        ostr.writeString(ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_isConfigurationReady(ConfigurationService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        int iceP_mesaId;
        int iceP_electionId;
        iceP_mesaId = istr.readInt();
        iceP_electionId = istr.readInt();
        inS.endReadParams();
        boolean ret = obj.isConfigurationReady(iceP_mesaId, iceP_electionId, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        ostr.writeBool(ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_preloadConfigurations(ConfigurationService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        int[] iceP_mesaIds;
        int iceP_electionId;
        iceP_mesaIds = istr.readIntSeq();
        iceP_electionId = istr.readInt();
        inS.endReadParams();
        obj.preloadConfigurations(iceP_mesaIds, iceP_electionId, current);
        return inS.setResult(inS.writeEmptyParams());
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_getBatchConfigurations(ConfigurationService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        int[] iceP_mesaIds;
        int iceP_electionId;
        iceP_mesaIds = istr.readIntSeq();
        iceP_electionId = istr.readInt();
        inS.endReadParams();
        String[] ret = obj.getBatchConfigurations(iceP_mesaIds, iceP_electionId, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        ostr.writeStringSeq(ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_getDepartmentConfigurations(ConfigurationService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        int iceP_departmentId;
        int iceP_electionId;
        iceP_departmentId = istr.readInt();
        iceP_electionId = istr.readInt();
        inS.endReadParams();
        String[] ret = obj.getDepartmentConfigurations(iceP_departmentId, iceP_electionId, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        ostr.writeStringSeq(ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_getPuestoConfigurations(ConfigurationService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        int iceP_puestoId;
        int iceP_electionId;
        iceP_puestoId = istr.readInt();
        iceP_electionId = istr.readInt();
        inS.endReadParams();
        String[] ret = obj.getPuestoConfigurations(iceP_puestoId, iceP_electionId, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        ostr.writeStringSeq(ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_getConfigurationStatistics(ConfigurationService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        int iceP_electionId;
        iceP_electionId = istr.readInt();
        inS.endReadParams();
        String ret = obj.getConfigurationStatistics(iceP_electionId, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        ostr.writeString(ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_isElectionReadyForConfiguration(ConfigurationService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        int iceP_electionId;
        iceP_electionId = istr.readInt();
        inS.endReadParams();
        boolean ret = obj.isElectionReadyForConfiguration(iceP_electionId, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        ostr.writeBool(ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /** @hidden */
    final static String[] _iceOps =
    {
        "getBatchConfigurations",
        "getConfiguration",
        "getConfigurationStatistics",
        "getDepartmentConfigurations",
        "getPuestoConfigurations",
        "ice_id",
        "ice_ids",
        "ice_isA",
        "ice_ping",
        "isConfigurationReady",
        "isElectionReadyForConfiguration",
        "preloadConfigurations"
    };

    /** @hidden */
    @Override
    default java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceDispatch(com.zeroc.IceInternal.Incoming in, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        int pos = java.util.Arrays.binarySearch(_iceOps, current.operation);
        if(pos < 0)
        {
            throw new com.zeroc.Ice.OperationNotExistException(current.id, current.facet, current.operation);
        }

        switch(pos)
        {
            case 0:
            {
                return _iceD_getBatchConfigurations(this, in, current);
            }
            case 1:
            {
                return _iceD_getConfiguration(this, in, current);
            }
            case 2:
            {
                return _iceD_getConfigurationStatistics(this, in, current);
            }
            case 3:
            {
                return _iceD_getDepartmentConfigurations(this, in, current);
            }
            case 4:
            {
                return _iceD_getPuestoConfigurations(this, in, current);
            }
            case 5:
            {
                return com.zeroc.Ice.Object._iceD_ice_id(this, in, current);
            }
            case 6:
            {
                return com.zeroc.Ice.Object._iceD_ice_ids(this, in, current);
            }
            case 7:
            {
                return com.zeroc.Ice.Object._iceD_ice_isA(this, in, current);
            }
            case 8:
            {
                return com.zeroc.Ice.Object._iceD_ice_ping(this, in, current);
            }
            case 9:
            {
                return _iceD_isConfigurationReady(this, in, current);
            }
            case 10:
            {
                return _iceD_isElectionReadyForConfiguration(this, in, current);
            }
            case 11:
            {
                return _iceD_preloadConfigurations(this, in, current);
            }
        }

        assert(false);
        throw new com.zeroc.Ice.OperationNotExistException(current.id, current.facet, current.operation);
    }
}
