//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `VotingSystem.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package VotingSystem;

public class Candidate implements java.lang.Cloneable,
                                  java.io.Serializable
{
    public int id;

    public String nombre;

    public String partido;

    public Candidate()
    {
        this.nombre = "";
        this.partido = "";
    }

    public Candidate(int id, String nombre, String partido)
    {
        this.id = id;
        this.nombre = nombre;
        this.partido = partido;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        Candidate r = null;
        if(rhs instanceof Candidate)
        {
            r = (Candidate)rhs;
        }

        if(r != null)
        {
            if(this.id != r.id)
            {
                return false;
            }
            if(this.nombre != r.nombre)
            {
                if(this.nombre == null || r.nombre == null || !this.nombre.equals(r.nombre))
                {
                    return false;
                }
            }
            if(this.partido != r.partido)
            {
                if(this.partido == null || r.partido == null || !this.partido.equals(r.partido))
                {
                    return false;
                }
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::VotingSystem::Candidate");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, id);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, nombre);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, partido);
        return h_;
    }

    public Candidate clone()
    {
        Candidate c = null;
        try
        {
            c = (Candidate)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeInt(this.id);
        ostr.writeString(this.nombre);
        ostr.writeString(this.partido);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.id = istr.readInt();
        this.nombre = istr.readString();
        this.partido = istr.readString();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, Candidate v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public Candidate ice_read(com.zeroc.Ice.InputStream istr)
    {
        Candidate v = new Candidate();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<Candidate> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, Candidate v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<Candidate> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            return java.util.Optional.of(Candidate.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final Candidate _nullMarshalValue = new Candidate();

    /** @hidden */
    public static final long serialVersionUID = -7076070060824114544L;
}
