//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `VotingSystem.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package VotingSystem;

public class Citizen implements java.lang.Cloneable,
                                java.io.Serializable
{
    public int id;

    public String documento;

    public String nombre;

    public String apellido;

    public Citizen()
    {
        this.documento = "";
        this.nombre = "";
        this.apellido = "";
    }

    public Citizen(int id, String documento, String nombre, String apellido)
    {
        this.id = id;
        this.documento = documento;
        this.nombre = nombre;
        this.apellido = apellido;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        Citizen r = null;
        if(rhs instanceof Citizen)
        {
            r = (Citizen)rhs;
        }

        if(r != null)
        {
            if(this.id != r.id)
            {
                return false;
            }
            if(this.documento != r.documento)
            {
                if(this.documento == null || r.documento == null || !this.documento.equals(r.documento))
                {
                    return false;
                }
            }
            if(this.nombre != r.nombre)
            {
                if(this.nombre == null || r.nombre == null || !this.nombre.equals(r.nombre))
                {
                    return false;
                }
            }
            if(this.apellido != r.apellido)
            {
                if(this.apellido == null || r.apellido == null || !this.apellido.equals(r.apellido))
                {
                    return false;
                }
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::VotingSystem::Citizen");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, id);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, documento);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, nombre);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, apellido);
        return h_;
    }

    public Citizen clone()
    {
        Citizen c = null;
        try
        {
            c = (Citizen)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeInt(this.id);
        ostr.writeString(this.documento);
        ostr.writeString(this.nombre);
        ostr.writeString(this.apellido);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.id = istr.readInt();
        this.documento = istr.readString();
        this.nombre = istr.readString();
        this.apellido = istr.readString();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, Citizen v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public Citizen ice_read(com.zeroc.Ice.InputStream istr)
    {
        Citizen v = new Citizen();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<Citizen> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, Citizen v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<Citizen> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            return java.util.Optional.of(Citizen.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final Citizen _nullMarshalValue = new Citizen();

    /** @hidden */
    public static final long serialVersionUID = -1846048465323398873L;
}
